cite 'about-alias'
about-alias 'common composer abbreviations'

# Aliases
alias cab='composer about'
alias car='composer archive'
alias cb='composer browser'
alias ccpq='composer check-platform-reqs'
alias ccc='composer clear-cache'
alias cconf='composer config'
alias ccp='composer create-project'
alias cdep='composer depends'
alias cdiag='composer diagnose'
alias cdump='composer dump-autoload'
alias cdumpo='composer dump-autoload -o'
alias cex='composer exec'
alias cglob='composer global'
alias ch='composer help'
alias chome='composer home'
alias ci='composer install'
alias cinfo='composer info'
alias cinit='composer init'
alias clic='composer license'
alias clist='composer list'
alias cout='composer outdated'
alias cp='composer prohibits'
alias crem='composer remove'
alias creq='composer require'
alias creqd='composer require --dev'
alias crs='composer run-script'
alias cs='composer search'
alias csu='composer self-update'
alias cshow='composer show'
alias cstat='composer status'
alias csugg='composer suggest'
alias cupd='composer update'
alias cupg='composer upgrade'
alias cval='composer validate'
alias cwhy='composer why'
alias cwhyn='composer why-not'
