cite 'about-alias'
about-alias 'maven abbreviations'

alias mci='mvn clean install'
alias mi='mvn install'
alias mrprep='mvn release:prepare'
alias mrperf='mvn release:perform'
alias mrrb='mvn release:rollback'
alias mdep='mvn dependency:tree'
alias mpom='mvn help:effective-pom'
alias mcisk='mci -Dmaven.test.skip=true'
