cite 'about-alias'
about-alias 'Pacman system Arch'
## PACMAN              USE:Pacman0                       #
alias Pacman0='echo -e "Pacman1 update";echo -e "Pacman2 Search";echo -e "Pacman3 Install";echo -e "Pacman4 Unistall";echo -e "Pacman5 Forze update";'
alias Pacman1='sudo pacman -Syu' 
alias Pacman2='sudo pacman -Ss'  
alias Pacman3='sudo pacman -S'   
alias pacman4='sudo pacman -Rs'  
alias Pacman5='sudo pacman -Syy' 
# YAY                  USE:Yay0                           #
alias Yay0='echo -e "Yay1 update";echo -e "Yay2 Search";echo -e "Yay3 Install";echo -e "Yay4 Unistall";echo -e "Yay5 Fuerza Forze update";'
alias Yay1='sudo yay -Syu'
alias Yay2='sudo yay -Ss'
alias Yay3='sudo yay -S' 
alias Yay4='sudo yay -Rs'
alias Yay5='sudo yay -Syy'
# PAKKU                 USE:Pakku0                       #
alias Pakku0='echo -e "Pakku1 update";echo -e "Pakku2 Search";echo -e "Pakku3 Install";echo -e "Pakku4 Unistall";echo -e "Pakku5 Forze update";'
alias Pakku1='sudo pakku -Syu'
alias Pakku2='sudo pakku -Ss'
alias Pakku3='sudo pakku -S'  
alias Pakku4='sudo pukku -Rs'   
alias Pakku5='sudo pakku -Syy'
