cite 'about-alias'
about-alias 'common svn abbreviations'

# Aliases
alias svs='svn status'
alias sa='svn add'
alias sci='svn ci -m'
alias sco='svn co'
alias sup='svn up'
alias scu='svn cleanup'
alias sli='svn list'
alias sdel='svn delete'
alias sdif='svn diff'
alias slog='svn log'
alias smv='svn move'
