cite 'about-alias'
about-alias 'yarn package manager aliases'

# Aliases
alias ya='yarn'
alias yai='yarn init'
alias yaa='yarn add'
alias yaad='yarn add --dev'
alias yau='yarn upgrade'
alias yarm='yarn remove'
alias yaod='yarn outdated'
alias yapa='yarn pack'
alias yap='yarn publish'
alias yasu='yarn self-update'
alias yaru='yarn run'
alias yat='yarn test'
alias yacc='yarn cache clean'
alias yack='yarn check'
alias yals='yarn ls'
alias yain='yarn info'
alias yali='yarn licenses ls'
alias yaloi='yarn login'
alias yaloo='yarn logout'
