# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
# fail_fast: true
minimum_pre_commit_version: 1.18.1
exclude: "docs/_build/|vendor/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ".(md|rst)$"
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 38980559e3a605691d6579f96222c30778e5a69e  # frozen: 3.0.0
    hooks:
      - id: git-check  # Configure in .gitattributes
      - id: shellcheck
        files: "\\.(bash)$"
      - id: shfmt
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8  # frozen: v1.5.6
    hooks:
      # - id: forbid-crlf
      - id: remove-crlf
        exclude: ".bat$"
  - repo: local
    hooks:
      - id: dot-sh
        name: Check .sh files against bash-it requirements
        entry: ./hooks/dot-sh.sh
        language: system
        files: "\\.sh$"
        types: [file]
      - id: dot-bash
        name: Check .bash files against bash-it requirements
        entry: ./hooks/dot-bash.sh
        language: system
        files: "\\.bash$"
        types: [file]
      - id: clean-files-txt
        name: Check that clean_files.txt is sorted alphabetically.
        entry: ./hooks/check-clean-files-txt.sh
        language: system
        files: clean_files.txt
