#!/usr/bin/env bash

. "$BASH_IT/themes/powerline-multiline-blue/powerline-multiline-blue.base.bash"

POWERLINE_TEXT_COLOR=0
POWERLINE_CWD_COLOR=39
POWERLINE_LAST_STATUS_COLOR=196
POWERLINE_SCM_CLEAN_COLOR=2
POWERLINE_SCM_DIRTY_COLOR=2
POWERLINE_SCM_STAGED_COLOR=2
POWERLINE_SCM_UNSTAGED_COLOR=2
SCM_GIT_SHOW_DETAILS=false
SCM_GIT_SHOW_REMOTE_INFO=false

POWERLINE_PYTHON_VENV_CHAR=""
PYTHON_VENV_THEME_PROMPT_COLOR=220

CLOCK_THEME_PROMPT_COLOR=220
THEME_CLOCK_FORMAT="%a %b %d %H:%M:%S %Y"

POWERLINE_LEFT_PROMPT="cwd scm python_venv terraform ruby node"
POWERLINE_RIGHT_PROMPT="date"

safe_append_prompt_command __powerline_prompt_command
